# Digital Ocean App Platform Specification for BookedSolid AI Dashboard
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: bookedsolid-ai-dashboard
region: nyc

# Database Configuration
databases:
  - name: bookedsolid-db
    engine: PG
    version: "16"
    production: true
    cluster_name: bookedsolid-cluster
    db_name: bookedsolid
    db_user: bookedsolid_user

# Web Service (Next.js Application)
services:
  - name: web
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true

    build_command: |
      npm ci
      npx prisma generate
      npm run build

    run_command: npm start

    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    # Health Check Configuration
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # HTTP Configuration
    http_port: 3000

    # Environment Variables
    envs:
      # Next.js Configuration
      - key: NODE_ENV
        value: production

      - key: NEXTAUTH_URL
        value: ${APP_URL}

      - key: NEXTAUTH_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Database Connection (Auto-populated from database service)
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${bookedsolid-db.DATABASE_URL}

      - key: DIRECT_DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${bookedsolid-db.DATABASE_URL}

      # Retell AI Configuration
      - key: RETELL_WEBHOOK_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: RETELL_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Google OAuth (Optional - if using OAuth)
      - key: GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

    # Routes Configuration
    routes:
      - path: /

# Jobs (Database Migration)
jobs:
  - name: db-migrate
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true

    build_command: |
      npm ci
      npx prisma generate

    run_command: npx prisma migrate deploy

    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    kind: PRE_DEPLOY

    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${bookedsolid-db.DATABASE_URL}

# Static Assets (Optional - if you want to serve static files via CDN)
# static_sites:
#   - name: static-assets
#     github:
#       repo: your-username/your-repo-name
#       branch: main
#       deploy_on_push: true
#     build_command: npm run build
#     output_dir: .next/static
